#!/bin/sh
# Refuse a PR that changes a release-please-generated file.
#
# Usage: guard-generated-files.sh <base-sha> <head-sha> [<upstream-ref>]
#
# CHANGELOG.md and .release-please-manifest.json are written by release-please,
# never by hand. The one exception is a merge of upstream into this fork: it
# legitimately brings upstream's own release-please output with it. A guarded
# file is therefore allowed when, and only when, its content at <head-sha> is
# byte-identical to upstream's main as of the upstream commit the head merged:
# the merge base of <head-sha> and <upstream-ref>. Comparing against the tip of
# <upstream-ref> instead would turn an already-correct merge red the moment
# upstream cut its next release. Contents are compared as git blob ids, so
# "absent on both" also matches. Any other change fails. When <upstream-ref> is
# omitted or does not resolve, there is no exemption at all, so an unreachable
# upstream fails closed to the strict check.
set -eu

base=$1
head=$2
upstream=${3:-}

upstream_commit=""
if [ -n "$upstream" ]; then
  if git rev-parse -q --verify "${upstream}^{commit}" >/dev/null 2>&1; then
    upstream_commit=$(git merge-base "$head" "$upstream" 2>/dev/null || true)
  fi
  [ -n "$upstream_commit" ] || echo "warning: ${upstream} does not resolve or shares no history with ${head}; no upstream exemption" >&2
fi

files=$(git diff --name-only "${base}...${head}")

violated=""
for path in CHANGELOG.md .release-please-manifest.json; do
  printf '%s\n' "$files" | grep -qxF -- "$path" || continue
  if [ -n "$upstream_commit" ]; then
    head_blob=$(git rev-parse -q --verify "${head}:${path}" 2>/dev/null || echo absent)
    upstream_blob=$(git rev-parse -q --verify "${upstream_commit}:${path}" 2>/dev/null || echo absent)
    if [ "$head_blob" = "$upstream_blob" ]; then
      echo "${path}: byte-identical to upstream at ${upstream_commit}; allowed as upstream's release-please output."
      continue
    fi
  fi
  violated="${violated} ${path}"
done

if [ -n "$violated" ]; then
  {
    echo "::error::This PR modifies release-please-generated files:${violated}"
    echo
    echo "CHANGELOG.md and .release-please-manifest.json are auto-generated by"
    echo "release-please from conventional commits on main. Do not hand-edit them."
    echo "A merge of upstream may carry them only byte-identical to upstream's main."
    echo
    echo "If you want your change to appear in the next release notes, use a"
    echo "conventional commit message (feat/fix/docs/...). release-please will"
    echo "update these files in the next release PR automatically."
    echo
    echo "See CONTRIBUTING.md for the full contributor workflow."
  } >&2
  exit 1
fi

echo "OK: no hand-edited release-please-generated files."
